# Author: Georgy Shapchits <gogi.soft.gm@gmail.com>

version: "2"

services:
  master:
    image: goginet/gluster
    fip: 209.177.93.85
    size: s1
    ports:
      - 22
    environment:
      NODES: 3
    links:
      - slave-1
      - slave-2
      - slave-3

  slave-1:
    size: l1
    image: goginet/gluster

  slave-2:
    size: l3
    image: goginet/gluster

  slave-3:
    size: l3
    image: goginet/gluster